### ISSUE TITLE
Launchpad Pro

### ISSUE THREAD

**Issue by fietronic** [FMMT666/launchpad.py#1]
Launchpad Pro is coming out in spring will the code be updated to support the new RGB LEDs?

**Comment by FMMT666** [comment]
Yes, and I'll also add the current "S" and "Mini" variants shortly.
Still looking for a nicely working and platform independent MIDI solution, though...

**Comment by FMMT666** [comment]
300 bucks (O_O)
http://www.thomann.de/de/novation_launchpad_pro.htm

Well...

**Comment by FMMT666** [comment]
Launchpad Pro support is available (limited for now 1/2016)
