### ISSUE TITLE
Publish to PyPI

### ISSUE THREAD

**Issue by Miserlou** [FMMT666/launchpad.py#11]
Hey @FMMT666 - thanks for your awesome project! Just made my Christmas present even cooler by making it hackable! :-D

It'd be great if you could add a `setup.py` file to this repo and publish it to PyPi so I can use it as a library without having to vendor your work into my project directory! Then I could just `pip install launchpad` (or whatever you call it) and just import in my projects.

Thanks very much!
Rich

**Comment by FMMT666** [comment]
Yes, I guess creating a library is probably a good idea.
Will do that, but I guess it's a little bit too early for PyPi (et al.), at
least until the MIDI issues are solved (Windoze 10 SysEx messages).

**Comment by stewartadam** [comment]
Doing this would fix https://github.com/FMMT666/launchpad.py/issues/10 as well :)

I'm going to try and prepare a PR tonight.

**Comment by stewartadam** [comment]
@Miserlou note that now that the setup.py PR has been merged, although this project is not listed in PyPi it is still possible to do a `pip install .` after cloning the repo.

**Comment by FMMT666** [comment]
Done. Available via "launchpad_py"

**Comment by Miserlou** [comment]
This. Is. Yuge.
