### ISSUE TITLE
Figlet Text Broken on LP Mk2

### ISSUE THREAD

**Issue by Miserlou** [FMMT666/launchpad.py#12]
The demo's `LP.LedCtrlString( 'HELLO ', 0, 3, -1 )  # scroll "HELLO" from right to left` causes non-text to flash and scroll across. Look like just the button mapping is different.

**Comment by FMMT666** [comment]
Yep, confirmed.
Also noticed that...

**Comment by FMMT666** [comment]
Oh, I misinterpreted that.
I thought you meant the artifacts that remain on the display after "wide" characters
like "`*`" were scrolled.

For the "Mk2", use:
```
  LP.LedCtrlString( 'HELLO ', 0, 63, 0, -1 )		
  LP.LedCtrlString( <string>, <red>, <green>, <blue>, <direction> )

```
If `<blue>` is omitted "Mk1 compatibility mode" is turned on. I will remove that soon...

Anyway, I completely started to rework the scrolling functionality.
Right to left works [tm]. Left to right has still some issues [quickhack].

**Comment by FMMT666** [comment]
"Fixed" with a warning in the doc (compatibility mode).
Will be removed in the future.
