### ISSUE TITLE
Launchkey Mini support possible?

### ISSUE THREAD

**Issue by ErikBjare** [FMMT666/launchpad.py#18]
I've read that the Launchkey MK2 should be possible to support ([Programmers Reference Guide](https://global.novationmusic.com/support/downloads/launchkey-mk2-programmers-reference-guide)).

However, I recently aquired a Launchkey Mini (new to the game) but my brief attempts in trying to send midi commands to the Launchpad Mini have been fruitless.

Since I assume you have a lot better familiarity with the hardware: Would it be possible to implement support for the Launchkey and if so how? (not asking for an actual implementation, I could do that myself if only I could get it to respond to midi commands)

**Comment by FMMT666** [comment]
Mhh, let's see...

```~sound of ordering products via Internet~```

**Comment by FMMT666** [comment]
I added a class for the Launchkey Mini.
Right now, there's only InputStateRaw(), but it will grow over the next few
days (or weeks :-)

**Comment by ErikBjare** [comment]
Amazing, will check it out. Thanks! <3

**Comment by FMMT666** [comment]
As it seems, there is no (official) way to control the LEDs.

I am pretty sure that there are some undocumented features to
make that work, but for now, I leave this as it is...
