### ISSUE TITLE
Error on mac OS 10.10.3

### ISSUE THREAD

**Issue by ghost** [FMMT666/launchpad.py#2]
pygame-1.9.1release-python.org-32bit-py2.7-macosx10.3.mpkg
python-2.7.10-macosx10.6.pkg

$ arch -32 python launchpad_demo.py 
unable to initialize MIDI
Exception AttributeError: "'module' object has no attribute 'quit'" in <bound method __Midi.__del__ of <launchpad.__Midi instance at 0x1703918>> ignored
Traceback (most recent call last):
  File "launchpad_demo.py", line 49, in <module>
    main()
  File "launchpad_demo.py", line 20, in main
    LP.Open()                   # start it
  File "/Users/sebastian/Downloads/launchpad.py-master/launchpad.py", line 368, in Open
    self.idOut = self.midi.SearchDevice( name, True, False, number = number )
  File "/Users/sebastian/Downloads/launchpad.py-master/launchpad.py", line 139, in **getattr**
    return getattr( self.instanceMidi, name )
AttributeError: 'NoneType' object has no attribute 'SearchDevice'

**Comment by ghost** [comment]
update

**Comment by FMMT666** [comment]
Indeed, I never tested this on a Mac.
Let's see what I can do...

**Comment by FMMT666** [comment]
I finally found time to look into this, but no, it's not possible right now.
None of the PyGame's Mac versions come with Midi built in, due to some
issues with portmidi.
I am currently evaluating options to integrate another Midi lib, that will (tm)
support all platforms.

**Comment by wmealing** [comment]
Just to confirm, i think Fedora25 has this issue also.
