### ISSUE TITLE
This may sound dumb, but how do i use it?

### ISSUE THREAD

**Issue by jackschedel** [FMMT666/launchpad.py#20]

**Comment by FMMT666** [comment]
This tiny piece of software enables you to control a Novation Launchpad
from within Python, a programming language and use it for completely
different things than music.

For example, I have a Launchpad attached to a CNC miling machine and
another one as a controller for a, well - some kind of
RPikitchenradioalarmclockmessengernotifier :-)

Just program it to do whatever you want it to do...

**Comment by FMMT666** [comment]
Closing this. Glad I could help...
No seriously, just let us know if you need any further assistance :-)
