### ISSUE TITLE
alsa error

### ISSUE THREAD

**Issue by pmikstacki** [FMMT666/launchpad.py#21]
Can someone tell me what I'm doing wrong?
ALSA lib conf.c:3009:(snd_config_update_r) Cannot access file /etc/alsa/alsa.conf
ALSA lib seq.c:935:(snd_seq_open_noupdate) Unknown SEQ default
Did not find any Launchpads, meh...
Exception AttributeError: "'NoneType' object has no attribute 'quit'" in <bound method __Midi.__del__ of <launchpad_py.launchpad.__Midi instance at 0x7fa29dcd9128>> ignored

**Comment by FMMT666** [comment]
Can you check whether 'alsa.conf' exists in that path (/etc/alsa/)?
Another common place is /usr/share/alsa/.

It should belong to 'libasound2-data', but you can explicitly check
that with, e.g.:

`dpkg -S <path to alsa.conf>`

First fix could be just reinstalling 'libasound2-data'.

**Comment by Zeioth** [comment]
I solved the 'Cannot access file /etc/alsa/alsa.conf' error  @with:

    sudo ln -s /usr/share/alsa/alsa.conf /etc/alsa/alsa.conf

But I still have the error:

    Exception AttributeError: "'NoneType' object has no attribute 'quit'" in <bound method __Midi.__del__ of <launchpad_py.launchpad.__Midi instance at 0x7f0860cb3128>> ignored

My output of **dpkg -S /usr/share/alsa/**:

    libasound2-plugins:i386, libasound2-plugins:amd64, alsa-utils, pulseaudio, libasound2-data: /usr/share/alsa

So 'libasound2-data' is installed. Any idea?

**OS:** Ubuntu
**Pygame version:** 1.9.3

**Comment by FMMT666** [comment]
That 'quit' error is known and caused by the Midi implementation
of PyGame. It only appears upon quitting your program and won't
affect code execution in any way.

Does it work now, with the symbolic link you created?
Btw, my Ubuntu config is in /etc/alsa.

Did you ever had (or have) installed JACK in parallel to Alsa?
