### ISSUE TITLE
Plugging in the Launchpad after the script has started

### ISSUE THREAD

**Issue by dhilowitz** [FMMT666/launchpad.py#22]
Hi!

Thanks for a great library.

So I've been hacking together a version of Samplerbox that implements a Launchpad95-like scale mode using launchpad.py for the launchpad portion of the code: https://github.com/dhilowitz/SamplerBox/tree/feature/launchpad-support. The only hitch I've run into is that when I plug the Launchpad in after the start of the script, it seems that `lp.Check()` and `lp.ListAll()` doesn't see it. It's almost as if the ports that `launchpad.py` can see are completely static and no new MIDI ports can be found once the script is started. Am I doing something wrong?

Thanks!

**Comment by dhilowitz** [comment]
OK. I've fixed this. **I've made a new fork of launchpad.py that uses [python-rtmidi](https://github.com/SpotlightKid/python-rtmidi) library instead of PyGame** for MIDI stuff. Here is the fork: https://github.com/dhilowitz/launchpad.py/tree/switch-to-rtmidi. If you'd like me to make a pull request at any point, I'd be more than happy to.

**Comment by FMMT666** [comment]
Yep, the step away from PyGame is long overdue,
but "priorities", you know :-)

Looks nice! I made a build with https://github.com/gesellkammer/rtmidi2

Need to check some things and test it on various platforms
first, though...
Gimme some time...

**Comment by dhilowitz** [comment]
That's awesome! Would love for an "official" version of launchpad.py that used one of the **rtmidi** libraries. Let me know if you need any testing help.
