### ISSUE TITLE
Linux Issue

### ISSUE THREAD

**Issue by Stefano-Lecchi** [FMMT666/launchpad.py#23]
Hi !

I have a problem with the library on Linux.
I ran the example script "hello.py", in the folder "examples", to see if the communication between the launchpad and the library worked, but it seems to not recognize my launchpad mini.

I get this error : Exception AttributeError: "'NoneType' object has no attribute 'quit'" in <bound method __Midi.__del__ of <launchpad_py.launchpad.__Midi instance at 0x7fb062d2dc68>> ignored

I also installed Linux's drivers for the launchpad, but it doesn't work yet.
I am using "Elementary OS" version 0.4.1, kernel's version is 4.4.0.

Thanks for the support!

**Comment by FMMT666** [comment]
That error is known and related to an error in PyGame.
It only happens after your program quits and does not
affect its execution in any way.

It looks like your Launchpad is not recognized.
That might be related to you OS and a lack of Midi
support...

Are you using the original cable?

Can you try this minimal code:

```
import launchpad_py

lp = launchpad_py.Launchpad()
lp.ListAll()
lp.Open()
...
```

In case you have launchpad.py in the same directory and
did not install it, you have to use

`import launchpad`

instead.

**Comment by Stefano-Lecchi** [comment]
Hi !

I made some operation for the lack of midi support in my OS, and now it recognize my launchpad, but the library still doesn't find it. I also tried the code you put me in your comment.

yes, i'm using the original cable.

Thanking you in advance.

**Comment by FMMT666** [comment]
Overlooked your reply, sorry...
What is the output of "lp.ListAll()"?

**Comment by FMMT666** [comment]
Does it work if you execute it as root?
Just take a look at #24. Maybe that works for you...
