### ISSUE TITLE
Install Issue Fix (Easy)

### ISSUE THREAD

**Issue by M4xiGitHub** [FMMT666/launchpad.py#27]
I really love your module but it was very hard to install on Windows 10 (for me) I installed and uninstalled python like x100 times. But I found a really easy installation process. I have the IDE Pycharm and with it you can directly install your package. Go to "file/settings/Project:yourProjectname" then select Python2.x and click on the green + sign. Then search for launchpad_py and click install. It automatically installs itself. Then search for Pygame and also install it. DONE !!! about 10min max.
Hope I could help...
Thank you Devs

**Comment by malmeloo** [comment]
What do you mean with it was hard to install? Installing through pip is probably faster, except for if you want to edit the source.

**Comment by FMMT666** [comment]
I assume your problems were caused by a missing 'pip', right?
Once you have that installed (or probably just adjusted your
PATH variable), the rest "should" be easy...
Glad you were lucky \o/
