### ISSUE TITLE
"LedSetLightshow()" support for LaunchKey 

### ISSUE THREAD

**Issue by CYNOMALY** [FMMT666/launchpad.py#28]
Hello FMMT666,

First, thank you for the great "launchpad.py" project.
while working on one of my project I used your "launchpad.py" project and I was need to add a support for the built-in lightshow demo function in my LaunchKey 61 keyboard.

I was thought about adding a lightshow demo support for the LaunchKey using "LedSetLightshow()" function for example.

The main process to achieve this is by switch the LaunchKey 61 to "Basic Mode" by sending the following midi message:

_# channel: 159 (send all midi messages to channel 16); note: 12; velocity: 0_
basic_mode = (159, 12, 0)

Then, map the LaunchKey 61 pad midi notes:

_# LaunchKey pad mapping (104, 105: round buttons)_
color_pad = [36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 104, 105]

And implement a loop which sends a messages to the LaunchKey 61 keyboard:

_# channel: 159; note: random.choice(color_pad); velocity: random.randint(1, 127)_
msg = (159, random.choice(color_pad), random.randint(1, 127))

To clear the pad light there are two options:
1. switch to "Extended Mode":
extended_mode = (159, 12, 1)

2. send "0" to all LaunchKey pad notes:
msg = (159, <pad_note>, 0)

Since I'm not going to create another project for this "feature" :-) I think it can be helpful if you will add this functionality also to the projects.

Thanks again.

**Comment by FMMT666** [comment]
Do you mean the "hello.py" example code? The LED flickering?
Just asking because "LedSetLightshow()" only activates the
Dicer's built-in Lightshow...
