### ISSUE TITLE
Adapting your code for standalone grid practice

### ISSUE THREAD

**Issue by infermachine** [FMMT666/launchpad.py#3]
Hey, I've started adapting your code to work on a Raspberry Pi and added a few pieces that let me play wav samples by hitting the pads. I'm running into problems though... specifically the program will break if I play too many pads simultaneously (giving me an "x doesn't have y" attribute error).

Is this something you've played with at all/ can you give me any tips on how to achieve something more like what Marc Resibois has done? (https://www.youtube.com/watch?v=hRomgKe1OsM). You obviously know more about MIDI and Pygame than I do so any help is much appreciated!

**Comment by isti115** [comment]
Man, it would be so awesome!!! I tried to do something similar myself (I tried it with python, puredata, etc. on raspbian and arch linux too), and after running into many problems and eventually giving up, I messaged Marc asking him how he did it, but he still hasn't responded, so I kind of let go of this idea, but if you could somehow manage to get it to work than it would be the best portable instrument!! just think about it! A pi, a battery bank, a launchpad and ear/headphones is all you need to practice!

**Comment by infermachine** [comment]
Ok yeah you and I are totally on the same page haha! And I don't think we are the only ones that would appreciate having something like this.

Apparently Marc has been busy cause he just had a kid, but I got a message back from him earlier today telling me to check out samplebox (http://www.samplerbox.org/). It has somewhat clear instructions on how to build the electrical components and the software is taken care of by an image you can download and put on the RPi. I can keep you updated on my progress, or if you want to build one too we could help each other troubleshoot :smiling_imp:

**Comment by isti115** [comment]
Man, I'm so excited to try this out, but I will have to wait until tomorrow. I think that I will need to do the manual install process, because I have a Raspberry Pi 1 Model B, which uses ARMv6, and the prebuilt image on the site is for Raspberry Pi 2, which has ARMv7 architecture, and thus a bigger instruction set, but I hope that I will manage to make it work!
ps.: I don't think that I will build any of the outer parts. I might instead try to modify the software a bit to be able to switch between banks from the launchpad, or maybe a USB numpad, or something small like that.

**Comment by FMMT666** [comment]
Interesting, thanks!
Never heard about rtmidi-python (that's what Samplerbox uses) until know.
Looks like I should build this in, instead of PyGame's, somewhat broken, MIDI implementation.

**Comment by infermachine** [comment]
So I got the Samplerbox software running on my Rpi, but when I plug in my Launchpad and USB stick with the samples I'm not getting any audio... so either I'm missing something or it's too good to be true and doesn't 'just work'. Also I was trying to change some system files around and couldn't because the filesystem is read-only... Might actually be easier to learn about rtmidi-python and write the code from scratch...

**Comment by infermachine** [comment]
I got it to make sound, but the audio quality is really bad. They say in the FAQ that you need to get a DAC because the Rpi's soundcard sucks, but I call bullshit because when I run the pygame code the samples sound totally clean on my pi.

 Might actually be easier to learn about rtmidi-python and write the code from scratch...

**Comment by FMMT666** [comment]
I guess they mean that Wolfson I2S DAC shield, right?

Never tried playing samples on the RPi (yet).
Probably simply not powerful enough to play back multiple samples w/o the DAC's driver?
I can imagine that the original one might be the (quick and dirty hacked) culprit :-)

**Comment by FMMT666** [comment]
Currently evaluating new Midi implementations...

**Comment by dhilowitz** [comment]
For what it's worth, I've been hacking a version of samplerbox that includes a Launchpad scale mode: https://github.com/dhilowitz/SamplerBox/tree/feature/launchpad-support. Right now it only supports C Major, though... :)

**Comment by infermachine** [comment]
Woah cool, I'll check that out!
