### ISSUE TITLE
Won't detect my Launchpad...

### ISSUE THREAD

**Issue by wrybread** [FMMT666/launchpad.py#35]
I just bought a used Launchpad that I was hoping to use with this package and so far launchpad.py won't detect it.

When I run hello.py I get "Did not find any Launchpads, meh..."

I'm using Windows 7 with Python 2.7. The Launchpad driver is installed and the Launchpad works with the Automap program (it lights up and shows button presses on screen).

I'm not sure what model my Launchpad is, the model number on the back is NOVLPD01. Any idea which model I should choose in this package? And if this model is supported?

Thanks for any help!

**Comment by wrybread** [comment]
Update: working fine in Ubuntu! Whoo hoo! Running hello.py shows it as a Launchpad MK1/S/Mini.

I don't imagine anyone has any tips to get it working in Windows?

**Comment by FMMT666** [comment]
Could you post the Python and PyGame versions?
I don't have a Windoze 7 machine anymore, but maybe I can try
some things ...

Also, might it be possible for you to uninstall the driver and
test it again? I cannot remember whether or not I ever installed
a driver for the Mk1.
