### ISSUE TITLE
crash in conjunction to pygame.mixer.Sound

### ISSUE THREAD

**Issue by NeoCortex97** [FMMT666/launchpad.py#36]
My script crashes if i use pygame.mixer and launchpad at the same time. The crash occures when the fadeout of the Sound object finishes with:
```Fatal Python error: PyEval_SaveThread: NULL tstate```

Using Launchpad mk2 on ubuntu 18.04. 
Python version is 3.6.8 and pygame version is 1.9.6

**Comment by NeoCortex97** [comment]
Did more debugging and suspect pygame mixer to cause my bug

**Comment by stuartlangridge** [comment]
The underlying cause of this is probably an SDL bug, but in my experience it is possible to work around it by explicitly setting the frequency of the mixer. By default, in pygame 1, the mixer frequency is set to 22050; in pygame 2 it is set to 44100. Setting it to 44100 in pygame 1 stopped this crash happening for me:

```python
    pygame.mixer.pre_init(frequency=44100)
    pygame.init()
    pygame.mixer.init(frequency=44100)
```

It's not clear if both of these init settings for the mixer are needed, but it doesn't hurt to add both, and for me it stopped the crash.

**Comment by FMMT666** [comment]
Interesting.
Could you provide some more infos about your machine, OS, Python, PyGame versions?

Anything that I could do to trigger this crash?

**Comment by stuartlangridge** [comment]
An update: I'm not as sure that the above helps as I was :(
Using Python 3, and Pygame 1.9.6 from pip, on Ubuntu 18.04, causes the crash. The above 44100 fix seems to make it more intermittent but doesn't stop it.
Using Python 2, and Pygame 1.9.1release from the Ubuntu archives, the crash does not occur.
I think this is a Pygame version and SDL issue (that is: I think that Py3 + pygame 1.9.1release would probably work fine), but I can't confirm that.
