### ISSUE TITLE
Random latency on Raspberry Pi

### ISSUE THREAD

**Issue by afandian** [FMMT666/launchpad.py#37]
Thanks for this library, it's excellent and mostly works on a Raspberry Pi. To start with the LED control is responsive.

But, after a while (a few minutes) the LEDs slow down and eventually stop changing. Like I could issue a `LedCtrlRawRapid` to fill the pad, but it takes a few seconds before displaying. It seems like when I sent a lot of messages without pausing between them it makes it worse. I see no error messages. The Python code doesn't hang.

I don't know if this is to do with a buffer getting full, PyGame MIDI on Raspberry Pi or what. I can't see any secret flush methods I could call. 

The example seems to run fine.

Any ideas?

**Comment by FMMT666** [comment]
If that happens with a Pro pad, it's (almost certainly) caused by the
pressure events. Simply pushing a button creates hundreds of pressure
event messages.

No other fix possible but polling faster.

Take a look at this "fire demo", provided in the example folder.
Happens there too ...

**Comment by afandian** [comment]
This is a LaunchPad Mini, and I'm not pressing any buttons. I will try polling for buttons if that helps.

**Comment by afandian** [comment]
For what it's worth, the button poll reveals no buttons (not surprising, I'm not pressing any). 

Here's a Python3 program that's showing the latency.

```
import launchpad_py as launchpad
import time
lp = launchpad.Launchpad();
lp.Open()

def celebrate():
  colours = [(3, 0), (3, 1), (2, 1), (2, 2), (1, 2), (1, 3), (0, 3)]           
  colours = [lp.LedGetColor(r,g) for (r,g) in colours]
  colours_len = len(colours)
  buf = [0] * (9*9)
  for o in range(colours_len):
    time.sleep(0.05)
    for xy in range(9*9):
      i = (xy + o) % colours_len
      buf[xy] = colours[i]
    lp.LedCtrlXY(0, 0, 0,0)
    lp.LedCtrlRawRapid(buf)
```

When I run this, it gets to about 3 before the lights start changing:
```
for x in range(100):
  print(x)
  celebrate()
```

I would not be surprised if this was a PyGame on Raspberry Pi issue. But can you see if I did anything wrong?

(There is a separate question #38  about how to call `LedCtrlRawRapid`!)

**Comment by FMMT666** [comment]
Sorry, didn't see your response, I'll take a look at this.
Which Pi board and PyGame library are you using?
