### ISSUE TITLE
Support for Behringer Cmd Touch Tc64

### ISSUE THREAD

**Issue by MrStormCoder** [FMMT666/launchpad.py#4]
I am getting one Behringer Cmd Touch Tc64 and i wasn't sure if this tool would work with it. You should take a look, it's pretty much the same thing as LS: http://www.behringer.com/EN/Products/CMD-TOUCH-TC64.aspx

**Comment by FMMT666** [comment]
Didn't find any API reference from Behringer.
Only one sentence that mentions "Novation Launchpad compatibility mode", whatever that means.
But I'll keep an eye on it, thanks!

Funny, looks like Novation already reacted and dropped their prices for the "Mini".
Now both, the Behringer, as well as the Novation now sell for 79€ :-)

**Comment by MrStormCoder** [comment]
Lol yeah, once i get my Behringer I'm gonna test this API with it and make some addaptions, I'll let you know if it does work.

**Comment by FMMT666** [comment]
Tried to buy one, but I couldn't get my hands on one of those.
I was told someone made it work...
Press and hold the two mode buttons on the top left while plugging the device in.
This toggles the Launchpad-S compatibility mode on or off (LEDs flash red or green then).
It might be required to change the name-lookup string in launchpad.py...
