### ISSUE TITLE
Launchpad Mk3 mini

### ISSUE THREAD

**Issue by pstaszko** [FMMT666/launchpad.py#41]
I don't see specific references to the Launchpad Mk3 mini. Is it supported? If not, is that planned?

**Comment by FMMT666** [comment]
I didn't know that existed. Ordered one.
Yep, will be added ...

**Comment by SteelEdgedKnife** [comment]
Any news on the Launchpad Mini MK3? Can test if needed...

**Comment by SteelEdgedKnife** [comment]
#41 Any possible workarounds to enable support for the mk3?

**Comment by SteelEdgedKnife** [comment]
Any possible workarounds to enable support for the mk3?

**Comment by FMMT666** [comment]
Only a few lines of code written yet, but it's basically working.
Use class "LaunchpadMk3" and yes, that also works for the Mini.
Find some example code in "hello.py".

Not on PyPi yet, of course; you'll need to use this Github repo here ...

**Comment by FMMT666** [comment]
Shall work now.
Not on PyPi yet, true.
