### ISSUE TITLE
Launchpad Mk2 Mini

### ISSUE THREAD

**Issue by karrika** [FMMT666/launchpad.py#42]
I just got a reduced price Launchpad Mini Mk2 pad that is not recognized. But it works perfectly by just banging bytes to/from /dev/dmmidi device. So I have full control of the buttons, the leds (just 2 bits per led. Red and green led only)

If you want me to try some special commands for getting the pad to identify properly I can do it.

My OS is Ubuntu 18.04

**Comment by karrika** [comment]
The top row of the pad. Buttons 1 2 3 4 5 6 7 8 can be controlled by 0xB0 h,i,j,k,l,m,n,o colour.
The rest of the buttons react to 0x90 position colour.
The colour seems to be g1 g0 x x r1 r0.
Button presses return triples like 0x90 position 0x7f (pressed) and 0x90 position 0x00 (released)

**Comment by FMMT666** [comment]
Hi,
yes, your Launchpad will not be recognized by a stock Ubuntu 18.04.
You need to compile your own version of PyGame.

Please check launchpad.py's "README.md" file (using "18.04" as a search
term should lead you to the corresponding parts) on how to do that.

**Comment by karrika** [comment]
Thanks. As I only need to read a button and light up a led using pygame seems like overkill.
Perhaps I try launchpad.py when pygame catches up with the main repository of Ubuntu.

I am writing a Retro Music application for composing game music for Atari Lynx. A little like Ableton but using the SASS music language instead of Midi and friends. The audio rendering will be by the Atari Lynx hardware itself.

**Comment by FMMT666** [comment]
Yep, probably not worth compiling it (though it's a matter of minutes).
Have some Lynx (Lynxs?) in the basement. Maybe I'll get back to you :)
