### ISSUE TITLE
Tested LP Mini MK3, doesn't work

### ISSUE THREAD

**Issue by SteelEdgedKnife** [FMMT666/launchpad.py#44]
attempted to use it with the LPHK software, the mini MK3 was able to be color flushed and colors put on the pads, but no actions can be performed by the launchpad, any ideas as to what to do?

**Comment by FMMT666** [comment]
What is LPHK?

"No actions" means that the button pushes are not recognized?
If so, did you open the 2nd device, e.g.

```  lp.Open( 1, "mk3) ```

So "1" instead of "0". Also, please check if the "hello.py" demo
file works for you.

**Comment by SteelEdgedKnife** [comment]
LPHK is an implementation of launchpad.py, linked here https://github.com/nimaid/LPHK and uses the launchpad.py to activate macros, currently the implementation doesnt work

**Comment by FMMT666** [comment]
Does it work now?

**Comment by waltervolkers** [comment]
In Hello.py i changed this !
And is now working !!!

if lp.Open( 1, "Mini Mk3" ):



Informations.py show this:

Running...
 - OS      : posix
 - Platform: Linux
 - Release : 5.4.0-56-generic
 - Arch    : 64bit
 - struct  : 64
 - Python  : 3.8.5
 - PyGame  : 1.9.6

Available MIDI devices:
 0 (b'ALSA', b'Midi Through Port-0', 0, 1, 0)
 1 (b'ALSA', b'Midi Through Port-0', 1, 0, 0)
 2 (b'ALSA', b'Launchpad Mini MK3 MIDI 1', 0, 1, 0)
 3 (b'ALSA', b'Launchpad Mini MK3 MIDI 1', 1, 0, 0)
 4 (b'ALSA', b'Launchpad Mini MK3 MIDI 2', 0, 1, 0)
 5 (b'ALSA', b'Launchpad Mini MK3 MIDI 2', 1, 0, 0)

**Comment by FMMT666** [comment]
👍
