### ISSUE TITLE
[Question][Mini MK3-LPX] LedCtrlRaw backward compatibility

### ISSUE THREAD

**Issue by NullMember** [FMMT666/launchpad.py#46]
Hi,
New Launchpad Mini MK3 and Launchpad X use values between 0 and 127 for RGB led control. Internally it's still have 6-bit resolution but ignores bit zero from incoming RGB data. I want to contribute this project for MK3 and LPX support but I don't want to make a decision. For backward compatibility we can continue to use values between 0-63 and shift color data 1 bit left just before sending RGB data or we can expect a color values between 0-127. 
Thanks for this awesome project.

**Comment by FMMT666** [comment]
Oh yes, I completely overlooked that. Thanks!

Yes, I agree, a shift should be fine as no one ever will notice
a difference between the LSB being set or not.

**Comment by NullMember** [comment]
Thanks for fast response. I will open PR as soon as I get things working (tomorrow, I hope).
