### ISSUE TITLE
Issue with launchpad pro

### ISSUE THREAD

**Issue by xyzDamaskus** [FMMT666/launchpad.py#49]
I'm trying to run one of the scripts but it says
`Python 2.7.9`
 `PyGame 1.9.2pre`
 `Launchpad Pro: ERROR`
I updated my LP drivers but still nothing.

**Comment by FMMT666** [comment]
I just added a file "information.py" in the examples directory.
Could you please execute this?

**Comment by xyzDamaskus** [comment]
```
Running...
 - OS      : nt
 - Platform: Windows
 - Release : 8
 - Python  : 2.7.9
 - PyGame  : 1.9.2pre

Available MIDI devices:
('MMSystem', 'Microsoft MIDI Mapper', 0, 1, 0)
('MMSystem', 'Launchpad Pro', 1, 0, 0)
('MMSystem', 'MIDIIN2 (Launchpad Pro)', 1, 0, 0)
('MMSystem', 'MIDIIN3 (Launchpad Pro)', 1, 0, 0)
('MMSystem', 'Microsoft GS Wavetable Synth', 0, 1, 0)
('MMSystem', 'Launchpad Pro', 0, 1, 0)
('MMSystem', 'MIDIOUT2 (Launchpad Pro)', 0, 1, 0)
('MMSystem', 'MIDIOUT3 (Launchpad Pro)', 0, 1, 0)


goodbye ...
```

Do you think it's because there are two midi devices with one that is output and the other is input?

**Comment by FMMT666** [comment]
Thanks.
According to my notes, Windows indeed has some problems with PyGame 1.9.2.
Is there any reason you need this specific version?

Newer ones shall be available via pip. I don't have a current Windows/Python2
machine available, so I cannot check, but you could also find *unofficial* builds
for Python 2 here:
http://www.lfd.uci.edu/~gohlke/pythonlibs/#pygame

**Comment by xyzDamaskus** [comment]
I don't need a specific version of pygame. ill download it and try

**Comment by xyzDamaskus** [comment]
What version of python/pygame do you have?

**Comment by xyzDamaskus** [comment]
I reinstalled pygame/python to the latest versions and now it works.
