### ISSUE TITLE
Support for the Custom Firmware

### ISSUE THREAD

**Issue by YarosMallorca** [FMMT666/launchpad.py#55]
Hi,
I have been trying to work with my **launchpad pro** using this library and the problem is that when I use the stock firmware, it works fine, but when I run the custom firmware it just stops working.

Here is the **firmware by mat1jaczyyy** that I use: https://github.com/mat1jaczyyy/lpp-performance-cfw

Can you please add the compatibility with that firmware? I request it because 60% of the lanchpadders use this firmware.

Thanks!

**Comment by FMMT666** [comment]
>  I request it because 60% of the lanchpadders use this firmware.

Can you prove this claim? :-)

I did not manage to find any documentation.
If you organize the commands in a human readable form, I might
consider adding them, yes.

**Comment by YarosMallorca** [comment]
I figured it out already! Thanks for the help anyway!

**Comment by Brendonovich** [comment]
Can't verify the statistic but if you're into more technical launchpadding like with Apollo Studio then you're most likely using mat1jaczyyy's custom firmware. I could try adding them, would be some good practice for my lacklustre python skills 😂
