### ISSUE TITLE
Launchpad X behaving slow

### ISSUE THREAD

**Issue by YarosMallorca** [FMMT666/launchpad.py#59]
Launchpad pro-mk1 and launchpad-mk2 work fine, but the Launchpad X behaves very slow and laggy. Have you tested the issue yet?

**Comment by FMMT666** [comment]
Slow and laggy with your special firmware or with the original one?

**Comment by YarosMallorca** [comment]
With the original stock firmware

**Comment by FMMT666** [comment]
Could you please share some code?
The X has pressure events and they either need to be polled
quickly enough or the event queue needs to be deleted via ```ButtonFlush()```
