### ISSUE TITLE
Python 3

### ISSUE THREAD

**Issue by ilo-3a29** [FMMT666/launchpad.py#6]
Hi,
I'd like to use this in a project using python 3. Is there any chance you can convert it?

**Comment by FMMT666** [comment]
No (not yet).
Python 3 required PyGame 1.9.2+, which comes without any MIDI functionality built-in.  
I'm still looking for a more platform independent lib.

Added a Python 3 note to the README...

**Comment by ilo-3a29** [comment]
I can recommend mido as a midi library for python 3, you can see a (terrible, incomplete) launchpad implementation using it [at this gist](https://gist.github.com/kerbingamer376/33a2ec340f38694b4b165bef5f850d1d).
