### ISSUE TITLE
Launchpad X Open()    ERROR:AttributeError: 'array.array' object has no attribute 'tostring'

### ISSUE THREAD

**Issue by V1K1NGbg** [FMMT666/launchpad.py#62]
`import sys
import time
import pyautogui
import win32com.client as comctl
from playsound import playsound

try:
    import launchpad_py as launchpad
except ImportError:
    try:
        import launchpad
    except ImportError:
        sys.exit("error loading launchpad.py")

lp = launchpad.LaunchpadLPX()
if lp.Open(0):
    print("Launchpad X")
    mode = "Pro"
`
There isn't a value for Open() with which it manages to connect to my launchpad

**Comment by V1K1NGbg** [comment]
The error is self.devOut.write_sys_ex( timeStamp, array.array('B', [0xf0] + lstMessage + [0xf7] ).tostring() )
AttributeError: 'array.array' object has no attribute 'tostring'

**Comment by FMMT666** [comment]
Which Python and PyGame versions are you using?
Or simply run the "information.py" file from the example folder and post the results.

I guess I know what's going on here ...

**Comment by V1K1NGbg** [comment]
Running...
 - OS      : nt
 - Platform: Windows
 - Release : 10
 - Arch    : 64bit
 - struct  : 64
 - Python  : 3.9.1

Available MIDI devices:
 0 (b'MMSystem', b'Microsoft MIDI Mapper', 0, 1, 0)
 1 (b'MMSystem', b'LPX MIDI', 1, 0, 0)
 2 (b'MMSystem', b'MIDIIN2 (LPX MIDI)', 1, 0, 0)
 3 (b'MMSystem', b'Microsoft GS Wavetable Synth', 0, 1, 0)
 4 (b'MMSystem', b'LPX MIDI', 0, 1, 0)
 5 (b'MMSystem', b'MIDIOUT2 (LPX MIDI)', 0, 1, 0)

**Comment by V1K1NGbg** [comment]
- PyGame  : 2.0.1
i forgot about that

**Comment by FMMT666** [comment]
Indeed, didn't work. I fixed it.
Not on PyPI yet, please use this repo in the meantime.

Thanks for reporting!
