### ISSUE TITLE
Replacing pygame.midi with mido

### ISSUE THREAD

**Issue by sethtroisi** [FMMT666/launchpad.py#76]
`pygame` is a pretty heavy api and it doesn't work on my system because of ALSA hell.

[`mido`](https://mido.readthedocs.io/en/latest/index.html) is a midi wrapper around several backends. It defaults to `python-rtmidi` but also supports `pygame`. IMHO replacing the pygame dependance with mido is likely to help some people who are struggling to get alsa to work. 

If the replacement code was clean, Would you be open to replacing pygame with mido?

**Comment by FMMT666** [comment]
Nah, thanks. I tested that some time ago.

There are some forks of this project which are already using rtmidi,
maybe it's better if you use one of these instead.

**Comment by sethtroisi** [comment]
Thanks, I'll look into them.
