### ISSUE TITLE
Example scripts dont work

### ISSUE THREAD

**Issue by sl4shed** [FMMT666/launchpad.py#78]
I ran an example script and I installed launchpad-py with pip, but it errored saying that launchpad didn't exist. Then I tried installing launchpad with pip, and now it errors at .LaunchpadPro

What package is the right launchpad library and why is this happening?

```
Traceback (most recent call last):
  File "c:\Users\User\Desktop\Launched\Launched.py", line 126, in <module>
    main()
  File "c:\Users\User\Desktop\Launched\Launched.py", line 29, in main
    if launchpad.LaunchpadPro().Check( 0 ):
AttributeError: module 'launchpad' has no attribute 'LaunchpadPro'. Did you mean: 'LaunchPad'?
```

**Comment by sl4shed** [comment]
solved, needed pygame

**Comment by FMMT666** [comment]
Sounds as if it's worth to add some error checks.
Maybe I'll add a couple of lines for this.

**Comment by sl4shed** [comment]
defenetily agree. Slapping import into a try catch isnt the best thing to do.
