### ISSUE TITLE
LaunchPad LED's not working

### ISSUE THREAD

**Issue by Noxville** [FMMT666/launchpad.py#8]
Hey there. I'm trying to get this working on Windows 10 (x64). I've got Pygame 1.9.1, Python 2.7.

MIDI controller is set using

```
lp = launchpad.LaunchpadPro() 
a = lp.Open(0, "Pro")         
```

The demo random lights doesn't work, however pressing buttons does output the correct response for lp.ButtonStateRaw()

```
[33, 70]
[33, 0]
[33, 45]
[33, 0]
[34, 38]
[33, 29]
[34, 0]
[33, 0]
```

**Comment by FMMT666** [comment]
Will check this...

**Comment by FMMT666** [comment]
Mhh, seems to work fine here...

Fresh Python 2.7.12 and Pygame 1.9.1 install on a Windoze 10 x64 machine from
- https://www.python.org/ftp/python/2.7.12/python-2.7.12.msi
- http://pygame.org/ftp/pygame-1.9.1.win32-py2.7.msi

and simply running "python launchpad.py".

Did you set the Launchpad Pro to "Live" mode?
Hold the "Setup" button and push the top left (green) matrix button.
After that, "LIVE" is scrolling across the matrix and the LED stripe in the
frame, below the round "Solo" and the "Volume" buttons, should be green.

Can you post what ListAll() dumps?

**Comment by Noxville** [comment]
Sure, here's a more verbose dump:

C:\Python27>python.exe --version
Python 2.7.12

C:\Python27\Scripts>pip.exe freeze
pygame==1.9.1

lp = launchpad.LaunchpadPro()
lp.ListAll()

```
('MMSystem', 'Microsoft MIDI Mapper', 0, 1, 0)
('MMSystem', 'Launchpad Pro', 1, 0, 0)
('MMSystem', 'MIDIIN2 (Launchpad Pro)', 1, 0, 0)
('MMSystem', 'MIDIIN3 (Launchpad Pro)', 1, 0, 0)
('MMSystem', 'Microsoft GS Wavetable Synth', 0, 1, 0)
('MMSystem', 'Launchpad Pro', 0, 1, 0)
('MMSystem', 'MIDIOUT2 (Launchpad Pro)', 0, 1, 0)
('MMSystem', 'MIDIOUT3 (Launchpad Pro)', 0, 1, 0)
```

Yeah, this is in the Live-mode. I even changed to Note mode and then back. The green strip is on, but the volume button isn't green.

**Comment by FMMT666** [comment]
Yep, can reproduce that (or at least partly).
Can you confirm that these two work:

  LedCtrlRawByCode()
  LedCtrlXYByCode()

E.g.:
  LedCtrlRawByCode( 81, 5 )

**Comment by Noxville** [comment]
https://gist.github.com/Noxville/1662a2614cee42032bebbb4b993cf350

Works correctly (top left button is red).

But does throw the following error

```
Traceback (most recent call last):
  File "D:\code\launchpad\launchpad_demo.py", line 28, in <module>
    main()
  File "D:\code\launchpad\launchpad_demo.py", line 24, in main
    lp.Reset()
AttributeError: 'LaunchpadPro' object has no attribute 'Reset'
```

**Comment by FMMT666** [comment]
The problem is that the MIDI SysEx messages don't work, so
there's no quick fix. I need to think about that...
(And that's probably just another reason to finally drop PyGame.
That would also fix a lot of other things (and OS X (macOS)))

Yes, the Launchpad Pro does not have Reset().

**Comment by Noxville** [comment]
Cool. For my purposes, being able to do LedCtrlXYByCode is fine.

Here's a base example for what I'll do:

https://gist.github.com/Noxville/29b520c43248738d32c0a28b09889759

**Comment by FMMT666** [comment]
Fixed.
