### ISSUE TITLE
Documentation issue: it does work on OSX

### ISSUE THREAD

**Issue by stewartadam** [FMMT666/launchpad.py#9]
The documentation reads that launchpad.py won't work on OS X because of pygame, but I wanted to let you know that I've successfully tested a Launchpad MK1 on OS X 10.12 "Sierra" using pygame==1.9.2a0. I just needed to grab the drivers from Novation first to make it show up as a MIDI device.

**Comment by FMMT666** [comment]
Lol, you're right!
Just tested with macOS Sierra and Pygame V1.9.2b8 (via pip) and
it even does work without installing the drivers.

Thank you very much for pointing that out!
Will test some more and update the docs...

**Comment by FMMT666** [comment]
Added macOS Sierra, Apple Python and Pygame notes.

Also, you're now part of the documentation :-)
(I hope you're fine with that...)

**Comment by stewartadam** [comment]
Thanks for all your hard work on launchpad.py, it's made my hobby project (controlling a L3D cube) a lot easier :)
